config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cities#index'
  resources :neighborhoods, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
    resources :messages, only: :create
    get 'chat', on: :member
  end
  resources :users, only: [:index, :edit]
  resources :amenities, only: [:index]
  resources :cities, only: [:index]
  get '/profile', to: 'pages#profile', as: :profile
  get '/home', to: 'pages#home', as: :home

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/amenity.rb
class Amenity < ApplicationRecord
  has_many :neighborhood_amenities, dependent: :destroy
  has_many :user_amenities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :neighborhoods
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :neighborhood
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  belongs_to :city
  has_many :neighborhood_amenities, dependent: :destroy
  has_many :amenities, through: :neighborhood_amenities
  has_many :messages
end

# Adicionar coluna ao usuário neighborhood_id (opcional)
# Vai ser atualizado assim q selecionar um bairro e tb
# Tabela de user_amenities para salvar as amen q o user escolheu
# ela vai ser uma join table entre user e amenities
# # Ela vai ser salva na hora que o user escolher, vamos passar esse dado de um lugar para o outro.

app/models/neighborhood_amenity.rb
class NeighborhoodAmenity < ApplicationRecord
  belongs_to :amenity
  belongs_to :neighborhood
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :neighborhood
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_one_attached :photo
  has_many :messages, dependent: :destroy
  has_many :user_amenities
  belongs_to :neighborhood, optional: true
  has_many :amenities, through: :user_amenities
end

app/models/user_amenity.rb
class UserAmenity < ApplicationRecord
  belongs_to :amenity
  belongs_to :user
end

app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
  def index

  end

  private

  def amenity_params
    params.require(:amenity).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :name, :city])
     devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :name, :city])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @message = Message.new(message_params)
    @message.neighborhood = @neighborhood
    @message.user = current_user
    if @message.save

      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      redirect_to chat_neighborhood_path(@neighborhood, anchor: "message-#{@message.id}")
    else
      render "neighborhoods/show"
    end
  end
  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  def index
    @neighborhoods = Neighborhood.all.to_a
    if params[:amenities].present?
      amenities = params[:amenities].split(',')
      update_user_amenities(amenities)
    end
    current_user.amenities.each do |ameni|
      neigh_ids = ameni.neighborhood_amenities.where('quantity >= 5').pluck(:neighborhood_id)
      @neighborhoods.select! { |neighborhood| neigh_ids.include?(neighborhood.id) }
    end
  end

  def show
    @neighborhood = Neighborhood.find(params[:id])
    current_user.neighborhood = @neighborhood
    current_user.save
  end

  def destroy_user_amenities
    UserAmenity.where(user: current_user).destroy_all
  end

  def update_user_amenities(amenities)
    destroy_user_amenities
    amenities.each do |amenity|
      ameni = Amenity.find_by(name: amenity)
      UserAmenity.create(user_id: current_user.id, amenity_id: ameni.id)
    end
  end

  def chat
    @neighborhood = Neighborhood.find(params[:id])
    @message = Message.new
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def profile
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
  end

  def create
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @review = Review.new(review_params)
    @review.neighborhood = @neighborhood
    @review.user = current_user
    if @review.save
      redirect_to neighborhood_path(@neighborhood)
    else
      render "neighborhoods/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/amenities/index.html.erb
<hr class="hr-1">
<div class="container">

  <%= link_to cities_path do %>
  <i class="fas fa-arrow-left back-arrow"></i>
  <% end  %>

  <img class="logo" src="https://res.cloudinary.com/where2live/image/upload/v1606838131/where2Live/Assets/where2live-logo_tklfqh.svg">
  <h1>What are you looking for next to your new home?</h1>

  <hr class="hr-2 mb-4">

    <div class="justify-content-center">
      <div class="text-center">

        <div class="pt-4">
          <div class="row d-flex">
            <div class="clickable" data-amenity="supermarket">
              <i class="fas fa-shopping-cart"></i>
              <small class="small-supermercado">Market</small>
            </div>

            <div class="clickable" data-amenity="hospital">
              <i class="fas fa-stethoscope"></i>
              <small>Hospital</small>
            </div>
          </div>

          <div class="row d-flex">
            <div class="clickable" data-amenity="gym">
              <i class="fas fa-dumbbell"></i>
              <small>Gym</small>
            </div>

            <div class="clickable" data-amenity="mobility">
              <i class="fas fa-bicycle"></i>
              <small>Mobility</small>
            </div>
          </div>

          <div class="row d-flex">
            <div class="clickable" data-amenity="restaurant">
              <i class="fas fa-utensils"></i>
              <small>Restaurant</small>
            </div>

            <div class="clickable" data-amenity="school">
              <i class="fas fa-graduation-cap"></i>
              <small>School</small>
            </div>

          </div>

        </div>
      </div>
    </div>


  <button class='btn btn-primary w-100' id="btn-amenities">
    Next step <i class="fas fa-angle-right"></i>
  </button>

</div>

app/views/cities/index.html.erb
<hr class="hr-1">
<div class="container">
  <img class="logo" src="https://res.cloudinary.com/where2live/image/upload/v1606838131/where2Live/Assets/where2live-logo_tklfqh.svg">
  <h1>Which city do you <br> want to live?</h1>

  <hr class="hr-2 mb-4">

  <form>
    <div class="form-group">
      <label for="exampleInputEmail1">Search your city below</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="ex: São Paulo">
    </div>

  <h4>(Don't worry, you can change this later).</h4>

 <%= link_to amenities_path, class: 'btn btn-primary w-100', id: "btn-ameni"  do %>
  Next step <i class="fas fa-angle-right"></i>
  <% end  %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>where2live</title>
    <link rel="icon" type="image/png" href="https://res.cloudinary.com/where2live/image/upload/v1606836143/where2Live/Assets/where2live-icon-1_agi83h.svg">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%# <!-- app/views/layouts/application.html.erb -->
    <body> %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%# </body> %>

    <%= yield %>
    <script type="text/javascript">
      // alert("<%#= params[:action] %>")
      <% if params[:action] == "show" %>
      const iconMarker = document.querySelector(".fa-map-marker-alt")
      if (iconMarker) {
        iconMarker.classList.add("active")
      }

      <% elsif params[:action] == "index" %>
      const iconStar = document.querySelector(".fa-star")
        if (iconStar) {
          iconStar.classList.add("active")
        }

      <% elsif params[:action] == "show" %>
      const iconUser = document.querySelector(".fa-user")
        if (iconUser) {
          iconUser.classList.add("active")
        }
      <% end %>
    </script>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="message-container" id="message-<%= message.id %>">
  <i class="author">
    <span><%= message.user %></span>
    <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
  </i>
  <p><%= message.content %></p>
</div>

app/views/neighborhoods/chat.html.erb
<hr class="hr-1">
<div class="container">

  <%= link_to neighborhood_reviews_path(current_user.neighborhood) do %>
  <i class="fas fa-arrow-left back-arrow"></i>
  <% end  %>

<h1><%= @neighborhood.name %></h1>
  <hr class="hr-2 mb-4">

<div id="messages" data-neighborhood-id="<%= @neighborhood.id if @neighborhood.id %>">
  <% @neighborhood.messages.each do |message| %>
    <div class="message-container" id="message-<%= message.id %>">
      <i class="author">
        <span><%= message.user.name %></span>
        <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
      </i>
      <p><%= message.content %></p>
      <hr class="hr-2 mb-4">
    </div>
  <% end %>
</div>

<%= simple_form_for [ @neighborhood, @message ], remote: true do |f| %>
  <%= f.input :content, label: false, placeholder: "Write your message here" %>
<% end %>
</div>

app/views/neighborhoods/index.html.erb
<hr class="hr-1">
<div class="container">

  <%= link_to amenities_path do %>
  <i class="fas fa-arrow-left back-arrow"></i>
  <% end  %>

  <img class="logo" src="https://res.cloudinary.com/where2live/image/upload/v1606838131/where2Live/Assets/where2live-logo_tklfqh.svg">
  <h1>Almost there! Now select your neighborhood <i class="far fa-smile"></i></h1>

  <form>
    <div class="form-group">
    </div>

  <table class="table">
    <tbody>
        <% @neighborhoods.each do |neighborhood| %>
        <tr>
          <td>
            <%= link_to neighborhood.name, neighborhood_path(neighborhood, amenities:  params[:amenities])  %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>

</div>

app/views/neighborhoods/show.html.erb
<form novalidate="novalidate" class="simple_form search" action="" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control">
    <input class="form-control form-control-sm" type="text" placeholder="🔎  Search for city, neighborhood or street"
        aria-label="Search">
    <!-- <button name="button" type="submit" class="btn btn-flat"> </button> -->
  </div>
</form>

<iframe class="map"
  width="100%"
  height="80%"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/search?key=<%= ENV["GOOGLE_API_SERVER_KEY"] %>&q=<%=@neighborhood.name%>+sao+paulo" allowfullscreen=""
  aria-hidden="false" tabindex="0">
</iframe>

<%= render 'shared/navbar' %>

app/views/pages/home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-home">
  <a class="navbar-brand" href="#">
    <img src="https://res.cloudinary.com/where2live/image/upload/v1606838131/where2Live/Assets/where2live-logo_tklfqh.svg" />
</a>
<p class="slogan-home">A safe place to find your new place</p>
</div>
<div class="banner" style="background-image: url(https://res.cloudinary.com/where2live/image/upload/v1607441424/where2Live/Images/city-bg-2_cp0wlb.jpg);">
  <div class="banner-container">
    <h1 class="ml12">A safe place to find your new place</h1>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <a class="btn btn-ghost" href="#">Download the app!</a>
  </div>
</div>
<div class="app-container">
  <div class="grid-app">
    <div class="grid-item">
      <h2 class="title-download">Download the app</h2>
      <p class="content-download">And find your new home today!</p>
      <img class="store-btn" src="https://res.cloudinary.com/where2live/image/upload/v1607380247/where2Live/Images/btn-google-play_dix7zd.png">
      <br>
      <img class="store-btn" src="https://res.cloudinary.com/where2live/image/upload/v1607380247/where2Live/Images/btn-app-store_qewr5a.png">
    </div>
    <div class=grid-item>
      <img class="phone-mockup" src="https://res.cloudinary.com/where2live/image/upload/v1607434517/where2Live/Images/iphone-mockup_ca8ozg.png">
    </div>
  </div>
</div>
  <div class="background-section">
    <div class="who-container">
      <div class="grid-who">
        <div class="grid-item">
          <div class="card">
            <img class="who-icon" src="https://res.cloudinary.com/where2live/image/upload/v1607451214/where2Live/Images/Artboard_3_kqhj1c.svg">
            <h3 class="who-title">Real Reviews</h3>
            <p class="who-content">We have a plentiful list of neighborhoods with real reviews of locals and passerbys helping you find the perfect match for your needs.</p>
          </div>
        </div>
        <div class=grid-item>
          <div class="card">
            <img class="who-icon" src="https://res.cloudinary.com/where2live/image/upload/v1607451214/where2Live/Images/Artboard_4_zi8byq.svg">
            <h3 class="who-title">Find New Places</h3>
            <p class="who-content">Discover new places that best suit your needs, search for cities, neighborhoods or streets and see what's nearby in the choosen area.</p>
          </div>
        </div>
        <div class=grid-item>
          <div class="card">
            <img class="who-icon" src="https://res.cloudinary.com/where2live/image/upload/v1607451214/where2Live/Images/Artboard_5_ka2vf2.svg">
            <h3 class="who-title">Our Community</h3>
            <p class="who-content">Don't feel lost anymore. Get in touch with trustful people who want to help you with tips and tricks with the whereabouts of your new home.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="city-banner">
    <img class="city-logo" src="https://res.cloudinary.com/where2live/image/upload/v1607454381/where2Live/Assets/where2live-logo-white_ovfze9.svg">
    <img class="city-img" src="https://res.cloudinary.com/where2live/image/upload/v1607454073/where2Live/Images/where2Live-banner-end_hucrom.png">
  </div>
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      I could've changed the footer but didn't, in honor of Le Wagon <i class="fas fa-heart"></i>
    </div>
  </div>

app/views/pages/profile.html.erb
<div class= "container-profile">
  <div class="banner-profile" >
    <div class="container text-center">
      <h1><%= current_user.name if current_user.name%></h1>
      <p><%= current_user.city if current_user.city %></p>
      <%= cl_image_tag current_user.photo.key, class: "avatar"  if current_user.photo.attached?%>
    </div>
  </div>

  <div class= "wls">
    <div class="container-btn">
      <%= link_to "", class: "btn btn-ghost-profile border-bottom" do %>
      <i class="far fa-comment-alt"></i> You have 0 Replies
      <% end %>
      <%= link_to "", class: "btn btn-ghost-profile border-bottom" do %>
      <i class="fas fa-pencil-alt"></i>  Edit profile
      <% end %>
      <%= link_to "", class: "btn btn-ghost-profile border-bottom" do %>
      <i class="far fa-star"></i> Add your review
      <% end %>
      <%= link_to "", class: "btn btn-ghost-profile border-bottom" do %>
      <i class="fas fa-wrench"></i> Configuration
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-ghost-profile border-bottom" do %>
      <i class="fas fa-sign-out-alt"></i> Sign out
      <% end %>
    </div>
  </div>

</div>
<%= render 'shared/navbar' %>

app/views/reviews/index.html.erb
<hr class="hr-1">
<div class="container">
  <h1>What people say about <%= @neighborhood.name %></h1>

  <hr class="hr-2 mb-4">

  <ul class="list-group list-group-flush">
    <li class="fas fa-shopping-cart icon-reviews"><span class="list-reviews"> Market</span></li>
    <li class="fas fa-stethoscope icon-reviews"><span class="list-reviews"> Hospital</span></li>
    <li class="fas fa-dumbbell icon-reviews"><span class="list-reviews"> Gym</span></li>
    <li class="fas fa-bicycle icon-reviews"><span class="list-reviews"> Mobility</span></li>
    <li class="fas fa-utensils icon-reviews"><span class="list-reviews"> Restaurant</span></li>
    <li class="fas fa-graduation-cap icon-reviews"><span class="list-reviews"> School</span></li>
  </ul>

  <hr class="hr-2 mb-4">

  <ul class="list-group list-group-flush">
    <%= link_to chat_neighborhood_path(@neighborhood) do %>
    <li class="far fa-comment-alt list-chat"><span class="list-message"> Join the chat now!</span></li>
    <% end  %>
  </ul>

  <hr class="hr-2 mb-4">

</div>

<%= render 'shared/navbar' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to neighborhoods_path do %>
  <i class="navbar-icon fas fa-arrow-left"></i>
  <% end  %>
  <%= link_to neighborhood_path(current_user.neighborhood) do %>
  <i class="navbar-icon fas fa-map-marker-alt"></i>
  <% end  %>
  <%= link_to neighborhood_reviews_path(current_user.neighborhood) do %>
  <i class="navbar-icon fas fa-star"></i>
  <% end  %>
  <%= link_to profile_path do %>
  <i class="navbar-icon fas fa-user"></i>
  <% end  %>

</div>